### ISSUE TITLE
Requirement Progress Has No Upper Bound

### ISSUE THREAD

**Issue by DonSeannelly** [rgott/cosc490#11]
When inputting a new event the Requirement Progress field can take any bound. This allows the user to achieve over the maximum points allotted.
![image](https://cloud.githubusercontent.com/assets/14933100/25644135/bc241b52-2f71-11e7-8585-43729c92b18e.png)

There are also certain requirements that can not be bound to an event as easily, such as "Current with SGA account." For this I would suggest that we replace the Requirement Progress input field with a form that allows the user to designate attendees to the event and the total number of hours each attendee was present. The controller would then calculate Requirement Progress to be stored in the database, as well as the total hours would be stored in association to each user.

Additionally, a new method for inputting non-event requirement progress would be needed.

**Comment by rgott** [comment]
which view is this on?

**Comment by rgott** [comment]
`/main/index` 
This check was left out (see below).
`if percentComplete > 1 then         percentComplete = 1           end`
