### ISSUE TITLE
update views (bootstrap)

### ISSUE THREAD

**Issue by rgott** [rgott/cosc490#14]
1. users/all views

container div added to these pages as well

**Comment by rgott** [comment]
- [x] /checkpoints/1/edit
- [x] /checkpoints/new
- [x] /events/1/edit
- [x] /events/new
- [x] login form in sidebar
- [x] go home when clicking on sidebar image
- [x] reduce sidebar image size and put on our server
- [ ] put content on /presentation

**Comment by DonSeannelly** [comment]
@rgott is the goal here to just bootstrap the first 4 views in the checklist? Is there anything else that is being factored in?

**Comment by rgott** [comment]
the goal is all of the views the big thing was putting them in bootstrap containers

**Comment by DonSeannelly** [comment]
After our discussion today, presentation doesn't seem to be a needed view.
