### ISSUE TITLE
Login button changes colors on logout

### ISSUE THREAD

**Issue by rgott** [rgott/cosc490#21]
![image](https://cloud.githubusercontent.com/assets/17398132/25963228/93c0aec6-364e-11e7-981d-2d31ddd445c4.png)

**Comment by scott789** [comment]
I didn't experience this problem when I tried logging out. 
I ran it on localhost and on heroku and did not experience this issue.

**Comment by scott789** [comment]
@rgott Is it just your browser?

**Comment by rgott** [comment]
@scott789 I believe @DonSeannelly fixed this issue in a recent commit
