### ISSUE TITLE
Autocomplete Rendering in Wrong Location

### ISSUE THREAD

**Issue by DonSeannelly** [rgott/cosc490#29]
When typing in inputs, the autocomplete appears left of where the input is. It occurs for the login form
![image](https://cloud.githubusercontent.com/assets/14933100/26139473/de625bce-3a9e-11e7-9a24-873fb9d638dd.png)

However it doesn't happen every time:
![image](https://cloud.githubusercontent.com/assets/14933100/26139508/19e7b432-3a9f-11e7-82cc-da347316a324.png)

Can anyone reproduce this issue?

**Comment by scott789** [comment]
I think it's your browser. I could not replicate this.
