### ISSUE TITLE
Fix static width on progress container

### ISSUE THREAD

**Issue by rgott** [rgott/cosc490#5]
Text should not appear below progress bar but to the left of it.
Top 3 are acceptable but bottom one overflows
![image](https://cloud.githubusercontent.com/assets/17398132/25241748/1ccf7340-25c5-11e7-9b0a-30534b81d2bf.png)

**Comment by DonSeannelly** [comment]
I'm working on this now, will be done soon

**Comment by DonSeannelly** [comment]
Fixed with commit [4f256f96e2340cf376758426509ce5c98a44be34](https://github.com/rgott/cosc490/commit/4f256f96e2340cf376758426509ce5c98a44be34)
